--------------------------------------------------------
-- Archivo creado  - sábado-julio-20-2019   
--------------------------------------------------------
DROP TABLE "EDELBERTO2"."ADMIN" cascade constraints;
DROP TABLE "EDELBERTO2"."DETALLE_DOMICILIO" cascade constraints;
DROP TABLE "EDELBERTO2"."DOMICILIO" cascade constraints;
DROP TABLE "EDELBERTO2"."MESA" cascade constraints;
DROP TABLE "EDELBERTO2"."PRODUCTO" cascade constraints;
DROP TABLE "EDELBERTO2"."RESERVA" cascade constraints;
DROP TABLE "EDELBERTO2"."RESTAURANTE" cascade constraints;
DROP TABLE "EDELBERTO2"."TARJETA_CREDITO" cascade constraints;
DROP PACKAGE "EDELBERTO2"."ADMIN_TAPI";
DROP PACKAGE "EDELBERTO2"."DETALLE_DOMICILIO_TAPI";
DROP PACKAGE "EDELBERTO2"."DOMICILIO_TAPI";
DROP PACKAGE "EDELBERTO2"."MESA_TAPI";
DROP PACKAGE "EDELBERTO2"."PRODUCTO_TAPI";
DROP PACKAGE "EDELBERTO2"."RESERVA_TAPI";
DROP PACKAGE BODY "EDELBERTO2"."ADMIN_TAPI";
DROP PACKAGE BODY "EDELBERTO2"."DETALLE_DOMICILIO_TAPI";
DROP PACKAGE BODY "EDELBERTO2"."DOMICILIO_TAPI";
DROP PACKAGE BODY "EDELBERTO2"."MESA_TAPI";
DROP PACKAGE BODY "EDELBERTO2"."PRODUCTO_TAPI";
DROP PACKAGE BODY "EDELBERTO2"."RESERVA_TAPI";
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "EDELBERTO2"."ADMIN" 
   (	"ID_ADMIN" NUMBER(*,0), 
	"PASSWORD" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Table DETALLE_DOMICILIO
--------------------------------------------------------

  CREATE TABLE "EDELBERTO2"."DETALLE_DOMICILIO" 
   (	"ID_PEDIDO" NUMBER(*,0), 
	"ID_DOMICILIO" NUMBER(*,0), 
	"ID_PRODUCTO" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0), 
	"PRECIO_TOTAL" NUMBER, 
	"DOMICILIO_ID_DOMICILO" NUMBER(*,0), 
	"PRODUCTO_ID_PRODUCTO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Table DOMICILIO
--------------------------------------------------------

  CREATE TABLE "EDELBERTO2"."DOMICILIO" 
   (	"ID_DOMICILO" NUMBER(*,0), 
	"NOMBRECLIENTE" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(10 BYTE), 
	"NOMBRE_PRODUCTO" VARCHAR2(20 BYTE), 
	"PRECIO" NUMBER, 
	"CANTIDAD" NUMBER(*,0), 
	"RESTAURANTE_ID_RESTAURANTE" NUMBER(*,0), 
	"TARJETA_CREDITO_NO_TARJ_CRED" VARCHAR2(20 BYTE), 
	"CELULAR" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Table MESA
--------------------------------------------------------

  CREATE TABLE "EDELBERTO2"."MESA" 
   (	"NO_MESA" NUMBER(*,0), 
	"DISPONIBILIDAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "EDELBERTO2"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER(*,0), 
	"NOMBRE_PRODUCTO" VARCHAR2(20 BYTE), 
	"COSTO" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Table RESERVA
--------------------------------------------------------

  CREATE TABLE "EDELBERTO2"."RESERVA" 
   (	"ID_RESERVA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"CANTIDAD_MESA" NUMBER(*,0), 
	"RESTAURANTE_ID_RESTAURANTE" NUMBER(*,0), 
	"TARJETA_CREDITO_NO_TARJ_CRED" VARCHAR2(20 BYTE), 
	"MESA_NO_MESA" NUMBER(*,0), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Table RESTAURANTE
--------------------------------------------------------

  CREATE TABLE "EDELBERTO2"."RESTAURANTE" 
   (	"ID_RESTAURANTE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"ADMIN_ID_ADMIN" NUMBER(*,0), 
	"CANTIDAD_MESAS_DISP" NUMBER(*,0), 
	"CANTIDAD_MESAS_OCUPADAS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Table TARJETA_CREDITO
--------------------------------------------------------

  CREATE TABLE "EDELBERTO2"."TARJETA_CREDITO" 
   (	"NO_TARJ_CRED" VARCHAR2(20 BYTE), 
	"CVV" NUMBER(*,0), 
	"FECHA_VENCIMIENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
REM INSERTING into EDELBERTO2.ADMIN
SET DEFINE OFF;
Insert into EDELBERTO2.ADMIN (ID_ADMIN,PASSWORD,NOMBRE) values ('123','edel','edelberto');
REM INSERTING into EDELBERTO2.DETALLE_DOMICILIO
SET DEFINE OFF;
REM INSERTING into EDELBERTO2.DOMICILIO
SET DEFINE OFF;
REM INSERTING into EDELBERTO2.MESA
SET DEFINE OFF;
Insert into EDELBERTO2.MESA (NO_MESA,DISPONIBILIDAD) values ('8','0');
REM INSERTING into EDELBERTO2.PRODUCTO
SET DEFINE OFF;
Insert into EDELBERTO2.PRODUCTO (ID_PRODUCTO,NOMBRE_PRODUCTO,COSTO,CANTIDAD) values ('123','fruta','200','33');
Insert into EDELBERTO2.PRODUCTO (ID_PRODUCTO,NOMBRE_PRODUCTO,COSTO,CANTIDAD) values ('2222','manzana','3000','2');
Insert into EDELBERTO2.PRODUCTO (ID_PRODUCTO,NOMBRE_PRODUCTO,COSTO,CANTIDAD) values ('111','NombreProducto','3','5');
REM INSERTING into EDELBERTO2.RESERVA
SET DEFINE OFF;
Insert into EDELBERTO2.RESERVA (ID_RESERVA,NOMBRE,CANTIDAD_MESA,RESTAURANTE_ID_RESTAURANTE,TARJETA_CREDITO_NO_TARJ_CRED,MESA_NO_MESA,FECHA) values ('334','Elias','4','8765','123456789','8',to_date('03/02/02','DD/MM/RR'));
Insert into EDELBERTO2.RESERVA (ID_RESERVA,NOMBRE,CANTIDAD_MESA,RESTAURANTE_ID_RESTAURANTE,TARJETA_CREDITO_NO_TARJ_CRED,MESA_NO_MESA,FECHA) values ('123','kendy','1','8765','123456789','8',to_date('18/07/19','DD/MM/RR'));
Insert into EDELBERTO2.RESERVA (ID_RESERVA,NOMBRE,CANTIDAD_MESA,RESTAURANTE_ID_RESTAURANTE,TARJETA_CREDITO_NO_TARJ_CRED,MESA_NO_MESA,FECHA) values ('333','Elias','4','8765','123456789','8',to_date('03/02/02','DD/MM/RR'));
Insert into EDELBERTO2.RESERVA (ID_RESERVA,NOMBRE,CANTIDAD_MESA,RESTAURANTE_ID_RESTAURANTE,TARJETA_CREDITO_NO_TARJ_CRED,MESA_NO_MESA,FECHA) values ('12','Elias','3456','8765','123456789','8',to_date('31/12/11','DD/MM/RR'));
REM INSERTING into EDELBERTO2.RESTAURANTE
SET DEFINE OFF;
Insert into EDELBERTO2.RESTAURANTE (ID_RESTAURANTE,NOMBRE,ADMIN_ID_ADMIN,CANTIDAD_MESAS_DISP,CANTIDAD_MESAS_OCUPADAS) values ('8765','fghj','123','98765','23456');
REM INSERTING into EDELBERTO2.TARJETA_CREDITO
SET DEFINE OFF;
Insert into EDELBERTO2.TARJETA_CREDITO (NO_TARJ_CRED,CVV,FECHA_VENCIMIENTO) values ('123456789','444',to_date('03/05/30','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDELBERTO2"."ADMIN_PK" ON "EDELBERTO2"."ADMIN" ("ID_ADMIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDELBERTO2"."PRODUCTO_PK" ON "EDELBERTO2"."PRODUCTO" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Index DETALLE_DOMICILIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDELBERTO2"."DETALLE_DOMICILIO_PK" ON "EDELBERTO2"."DETALLE_DOMICILIO" ("ID_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Index TARJETA_CREDITO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDELBERTO2"."TARJETA_CREDITO_PK" ON "EDELBERTO2"."TARJETA_CREDITO" ("NO_TARJ_CRED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Index DOMICILIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDELBERTO2"."DOMICILIO_PK" ON "EDELBERTO2"."DOMICILIO" ("ID_DOMICILO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Index RESERVA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDELBERTO2"."RESERVA_PK" ON "EDELBERTO2"."RESERVA" ("ID_RESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Index MESA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDELBERTO2"."MESA_PK" ON "EDELBERTO2"."MESA" ("NO_MESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Index RESTAURANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDELBERTO2"."RESTAURANTE_PK" ON "EDELBERTO2"."RESTAURANTE" ("ID_RESTAURANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA" ;
--------------------------------------------------------
--  DDL for Package ADMIN_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "EDELBERTO2"."ADMIN_TAPI" 
is

type ADMIN_tapi_rec is record (
PASSWORD  ADMIN.PASSWORD%type
,ID_ADMIN  ADMIN.ID_ADMIN%type
,NOMBRE  ADMIN.NOMBRE%type
);
type ADMIN_tapi_tab is table of ADMIN_tapi_rec;

-- insert
procedure ins (
p_PASSWORD in ADMIN.PASSWORD%type default null 
,p_ID_ADMIN in ADMIN.ID_ADMIN%type
,p_NOMBRE in ADMIN.NOMBRE%type default null 
);
-- update
procedure upd (
p_PASSWORD in ADMIN.PASSWORD%type default null 
,p_ID_ADMIN in ADMIN.ID_ADMIN%type
,p_NOMBRE in ADMIN.NOMBRE%type default null 
);
-- delete
procedure del (
p_ID_ADMIN in ADMIN.ID_ADMIN%type
);
end ADMIN_tapi;


/
--------------------------------------------------------
--  DDL for Package DETALLE_DOMICILIO_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "EDELBERTO2"."DETALLE_DOMICILIO_TAPI" 
is

type DETALLE_DOMICILIO_tapi_rec is record (
PRODUCTO_ID_PRODUCTO  DETALLE_DOMICILIO.PRODUCTO_ID_PRODUCTO%type
,DOMICILIO_ID_DOMICILO  DETALLE_DOMICILIO.DOMICILIO_ID_DOMICILO%type
,ID_DOMICILIO  DETALLE_DOMICILIO.ID_DOMICILIO%type
,PRECIO_TOTAL  DETALLE_DOMICILIO.PRECIO_TOTAL%type
,ID_PEDIDO  DETALLE_DOMICILIO.ID_PEDIDO%type
,ID_PRODUCTO  DETALLE_DOMICILIO.ID_PRODUCTO%type
,CANTIDAD  DETALLE_DOMICILIO.CANTIDAD%type
);
type DETALLE_DOMICILIO_tapi_tab is table of DETALLE_DOMICILIO_tapi_rec;

-- insert
procedure ins (
p_PRODUCTO_ID_PRODUCTO in DETALLE_DOMICILIO.PRODUCTO_ID_PRODUCTO%type
,p_DOMICILIO_ID_DOMICILO in DETALLE_DOMICILIO.DOMICILIO_ID_DOMICILO%type
,p_ID_DOMICILIO in DETALLE_DOMICILIO.ID_DOMICILIO%type default null 
,p_PRECIO_TOTAL in DETALLE_DOMICILIO.PRECIO_TOTAL%type default null 
,p_ID_PEDIDO in DETALLE_DOMICILIO.ID_PEDIDO%type
,p_ID_PRODUCTO in DETALLE_DOMICILIO.ID_PRODUCTO%type default null 
,p_CANTIDAD in DETALLE_DOMICILIO.CANTIDAD%type default null 
);
-- update
procedure upd (
p_PRODUCTO_ID_PRODUCTO in DETALLE_DOMICILIO.PRODUCTO_ID_PRODUCTO%type
,p_DOMICILIO_ID_DOMICILO in DETALLE_DOMICILIO.DOMICILIO_ID_DOMICILO%type
,p_ID_DOMICILIO in DETALLE_DOMICILIO.ID_DOMICILIO%type default null 
,p_PRECIO_TOTAL in DETALLE_DOMICILIO.PRECIO_TOTAL%type default null 
,p_ID_PEDIDO in DETALLE_DOMICILIO.ID_PEDIDO%type
,p_ID_PRODUCTO in DETALLE_DOMICILIO.ID_PRODUCTO%type default null 
,p_CANTIDAD in DETALLE_DOMICILIO.CANTIDAD%type default null 
);
-- delete
procedure del (
p_ID_PEDIDO in DETALLE_DOMICILIO.ID_PEDIDO%type
);
end DETALLE_DOMICILIO_tapi;


/
--------------------------------------------------------
--  DDL for Package DOMICILIO_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "EDELBERTO2"."DOMICILIO_TAPI" 
is

type DOMICILIO_tapi_rec is record (
DIRECCION  DOMICILIO.DIRECCION%type
,PRECIO  DOMICILIO.PRECIO%type
,TARJETA_CREDITO_NO_TARJ_CRED  DOMICILIO.TARJETA_CREDITO_NO_TARJ_CRED%type
,NOMBRE_PRODUCTO  DOMICILIO.NOMBRE_PRODUCTO%type
,RESTAURANTE_ID_RESTAURANTE  DOMICILIO.RESTAURANTE_ID_RESTAURANTE%type
,CELULAR  DOMICILIO.CELULAR%type
,ID_DOMICILO  DOMICILIO.ID_DOMICILO%type
,NOMBRECLIENTE  DOMICILIO.NOMBRECLIENTE%type
,CANTIDAD  DOMICILIO.CANTIDAD%type
);
type DOMICILIO_tapi_tab is table of DOMICILIO_tapi_rec;

-- insert
procedure ins (
p_DIRECCION in DOMICILIO.DIRECCION%type default null 
,p_PRECIO in DOMICILIO.PRECIO%type default null 
,p_TARJETA_CREDITO_NO_TARJ_CRED in DOMICILIO.TARJETA_CREDITO_NO_TARJ_CRED%type
,p_NOMBRE_PRODUCTO in DOMICILIO.NOMBRE_PRODUCTO%type default null 
,p_RESTAURANTE_ID_RESTAURANTE in DOMICILIO.RESTAURANTE_ID_RESTAURANTE%type
,p_CELULAR in DOMICILIO.CELULAR%type default null 
,p_ID_DOMICILO in DOMICILIO.ID_DOMICILO%type
,p_NOMBRECLIENTE in DOMICILIO.NOMBRECLIENTE%type default null 
,p_CANTIDAD in DOMICILIO.CANTIDAD%type default null 
);
-- update
procedure upd (
p_DIRECCION in DOMICILIO.DIRECCION%type default null 
,p_PRECIO in DOMICILIO.PRECIO%type default null 
,p_TARJETA_CREDITO_NO_TARJ_CRED in DOMICILIO.TARJETA_CREDITO_NO_TARJ_CRED%type
,p_NOMBRE_PRODUCTO in DOMICILIO.NOMBRE_PRODUCTO%type default null 
,p_RESTAURANTE_ID_RESTAURANTE in DOMICILIO.RESTAURANTE_ID_RESTAURANTE%type
,p_CELULAR in DOMICILIO.CELULAR%type default null 
,p_ID_DOMICILO in DOMICILIO.ID_DOMICILO%type
,p_NOMBRECLIENTE in DOMICILIO.NOMBRECLIENTE%type default null 
,p_CANTIDAD in DOMICILIO.CANTIDAD%type default null 
);
-- delete
procedure del (
p_ID_DOMICILO in DOMICILIO.ID_DOMICILO%type
);
end DOMICILIO_tapi;


/
--------------------------------------------------------
--  DDL for Package MESA_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "EDELBERTO2"."MESA_TAPI" 
is

type MESA_tapi_rec is record (
DISPONIBILIDAD  MESA.DISPONIBILIDAD%type
,NO_MESA  MESA.NO_MESA%type
);
type MESA_tapi_tab is table of MESA_tapi_rec;

-- insert
procedure ins (
p_DISPONIBILIDAD in MESA.DISPONIBILIDAD%type default null 
,p_NO_MESA in MESA.NO_MESA%type
);
-- update
procedure upd (
p_DISPONIBILIDAD in MESA.DISPONIBILIDAD%type default null 
,p_NO_MESA in MESA.NO_MESA%type
);
-- delete
procedure del (
p_NO_MESA in MESA.NO_MESA%type
);
end MESA_tapi;


/
--------------------------------------------------------
--  DDL for Package PRODUCTO_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "EDELBERTO2"."PRODUCTO_TAPI" 
is

type PRODUCTO_tapi_rec is record (
NOMBRE_PRODUCTO  PRODUCTO.NOMBRE_PRODUCTO%type
,COSTO  PRODUCTO.COSTO%type
,ID_PRODUCTO  PRODUCTO.ID_PRODUCTO%type
,CANTIDAD  PRODUCTO.CANTIDAD%type
);
type PRODUCTO_tapi_tab is table of PRODUCTO_tapi_rec;

-- insert
procedure ins (
p_NOMBRE_PRODUCTO in PRODUCTO.NOMBRE_PRODUCTO%type default null 
,p_COSTO in PRODUCTO.COSTO%type default null 
,p_ID_PRODUCTO in PRODUCTO.ID_PRODUCTO%type
,p_CANTIDAD in PRODUCTO.CANTIDAD%type default null 
);
-- update
procedure upd (
p_NOMBRE_PRODUCTO in PRODUCTO.NOMBRE_PRODUCTO%type default null 
,p_COSTO in PRODUCTO.COSTO%type default null 
,p_ID_PRODUCTO in PRODUCTO.ID_PRODUCTO%type
,p_CANTIDAD in PRODUCTO.CANTIDAD%type default null 
);
-- delete
procedure del (
p_ID_PRODUCTO in PRODUCTO.ID_PRODUCTO%type
);
end PRODUCTO_tapi;


/
--------------------------------------------------------
--  DDL for Package RESERVA_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "EDELBERTO2"."RESERVA_TAPI" 
is

type RESERVA_tapi_rec is record (
TARJETA_CREDITO_NO_TARJ_CRED  RESERVA.TARJETA_CREDITO_NO_TARJ_CRED%type
,RESTAURANTE_ID_RESTAURANTE  RESERVA.RESTAURANTE_ID_RESTAURANTE%type
,FECHA  RESERVA.FECHA%type
,ID_RESERVA  RESERVA.ID_RESERVA%type
,CANTIDAD_MESA  RESERVA.CANTIDAD_MESA%type
,MESA_NO_MESA  RESERVA.MESA_NO_MESA%type
,NOMBRE  RESERVA.NOMBRE%type
);
type RESERVA_tapi_tab is table of RESERVA_tapi_rec;

-- insert
procedure ins (
p_TARJETA_CREDITO_NO_TARJ_CRED in RESERVA.TARJETA_CREDITO_NO_TARJ_CRED%type
,p_RESTAURANTE_ID_RESTAURANTE in RESERVA.RESTAURANTE_ID_RESTAURANTE%type
,p_FECHA in RESERVA.FECHA%type default null 
,p_ID_RESERVA in RESERVA.ID_RESERVA%type
,p_CANTIDAD_MESA in RESERVA.CANTIDAD_MESA%type default null 
,p_MESA_NO_MESA in RESERVA.MESA_NO_MESA%type
,p_NOMBRE in RESERVA.NOMBRE%type default null 
);
-- update
procedure upd (
p_TARJETA_CREDITO_NO_TARJ_CRED in RESERVA.TARJETA_CREDITO_NO_TARJ_CRED%type
,p_RESTAURANTE_ID_RESTAURANTE in RESERVA.RESTAURANTE_ID_RESTAURANTE%type
,p_FECHA in RESERVA.FECHA%type default null 
,p_ID_RESERVA in RESERVA.ID_RESERVA%type
,p_CANTIDAD_MESA in RESERVA.CANTIDAD_MESA%type default null 
,p_MESA_NO_MESA in RESERVA.MESA_NO_MESA%type
,p_NOMBRE in RESERVA.NOMBRE%type default null 
);
-- delete
procedure del (
p_ID_RESERVA in RESERVA.ID_RESERVA%type
);
end RESERVA_tapi;


/
--------------------------------------------------------
--  DDL for Package Body ADMIN_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "EDELBERTO2"."ADMIN_TAPI" 
is
-- insert
procedure ins (
p_PASSWORD in ADMIN.PASSWORD%type default null 
,p_ID_ADMIN in ADMIN.ID_ADMIN%type
,p_NOMBRE in ADMIN.NOMBRE%type default null 
) is
begin
insert into ADMIN(
PASSWORD
,ID_ADMIN
,NOMBRE
) values (
p_PASSWORD
,p_ID_ADMIN
,p_NOMBRE
);end;
-- update
procedure upd (
p_PASSWORD in ADMIN.PASSWORD%type default null 
,p_ID_ADMIN in ADMIN.ID_ADMIN%type
,p_NOMBRE in ADMIN.NOMBRE%type default null 
) is
begin
update ADMIN set
PASSWORD = p_PASSWORD
,NOMBRE = p_NOMBRE
where ID_ADMIN = p_ID_ADMIN;
end;
-- del
procedure del (
p_ID_ADMIN in ADMIN.ID_ADMIN%type
) is
begin
delete from ADMIN
where ID_ADMIN = p_ID_ADMIN;
end;
end ADMIN_tapi;

/
--------------------------------------------------------
--  DDL for Package Body DETALLE_DOMICILIO_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "EDELBERTO2"."DETALLE_DOMICILIO_TAPI" 
is
-- insert
procedure ins (
p_PRODUCTO_ID_PRODUCTO in DETALLE_DOMICILIO.PRODUCTO_ID_PRODUCTO%type
,p_DOMICILIO_ID_DOMICILO in DETALLE_DOMICILIO.DOMICILIO_ID_DOMICILO%type
,p_ID_DOMICILIO in DETALLE_DOMICILIO.ID_DOMICILIO%type default null 
,p_PRECIO_TOTAL in DETALLE_DOMICILIO.PRECIO_TOTAL%type default null 
,p_ID_PEDIDO in DETALLE_DOMICILIO.ID_PEDIDO%type
,p_ID_PRODUCTO in DETALLE_DOMICILIO.ID_PRODUCTO%type default null 
,p_CANTIDAD in DETALLE_DOMICILIO.CANTIDAD%type default null 
) is
begin
insert into DETALLE_DOMICILIO(
PRODUCTO_ID_PRODUCTO
,DOMICILIO_ID_DOMICILO
,ID_DOMICILIO
,PRECIO_TOTAL
,ID_PEDIDO
,ID_PRODUCTO
,CANTIDAD
) values (
p_PRODUCTO_ID_PRODUCTO
,p_DOMICILIO_ID_DOMICILO
,p_ID_DOMICILIO
,p_PRECIO_TOTAL
,p_ID_PEDIDO
,p_ID_PRODUCTO
,p_CANTIDAD
);end;
-- update
procedure upd (
p_PRODUCTO_ID_PRODUCTO in DETALLE_DOMICILIO.PRODUCTO_ID_PRODUCTO%type
,p_DOMICILIO_ID_DOMICILO in DETALLE_DOMICILIO.DOMICILIO_ID_DOMICILO%type
,p_ID_DOMICILIO in DETALLE_DOMICILIO.ID_DOMICILIO%type default null 
,p_PRECIO_TOTAL in DETALLE_DOMICILIO.PRECIO_TOTAL%type default null 
,p_ID_PEDIDO in DETALLE_DOMICILIO.ID_PEDIDO%type
,p_ID_PRODUCTO in DETALLE_DOMICILIO.ID_PRODUCTO%type default null 
,p_CANTIDAD in DETALLE_DOMICILIO.CANTIDAD%type default null 
) is
begin
update DETALLE_DOMICILIO set
PRODUCTO_ID_PRODUCTO = p_PRODUCTO_ID_PRODUCTO
,DOMICILIO_ID_DOMICILO = p_DOMICILIO_ID_DOMICILO
,ID_DOMICILIO = p_ID_DOMICILIO
,PRECIO_TOTAL = p_PRECIO_TOTAL
,ID_PRODUCTO = p_ID_PRODUCTO
,CANTIDAD = p_CANTIDAD
where ID_PEDIDO = p_ID_PEDIDO;
end;
-- del
procedure del (
p_ID_PEDIDO in DETALLE_DOMICILIO.ID_PEDIDO%type
) is
begin
delete from DETALLE_DOMICILIO
where ID_PEDIDO = p_ID_PEDIDO;
end;
end DETALLE_DOMICILIO_tapi;

/
--------------------------------------------------------
--  DDL for Package Body DOMICILIO_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "EDELBERTO2"."DOMICILIO_TAPI" 
is
-- insert
procedure ins (
p_DIRECCION in DOMICILIO.DIRECCION%type default null 
,p_PRECIO in DOMICILIO.PRECIO%type default null 
,p_TARJETA_CREDITO_NO_TARJ_CRED in DOMICILIO.TARJETA_CREDITO_NO_TARJ_CRED%type
,p_NOMBRE_PRODUCTO in DOMICILIO.NOMBRE_PRODUCTO%type default null 
,p_RESTAURANTE_ID_RESTAURANTE in DOMICILIO.RESTAURANTE_ID_RESTAURANTE%type
,p_CELULAR in DOMICILIO.CELULAR%type default null 
,p_ID_DOMICILO in DOMICILIO.ID_DOMICILO%type
,p_NOMBRECLIENTE in DOMICILIO.NOMBRECLIENTE%type default null 
,p_CANTIDAD in DOMICILIO.CANTIDAD%type default null 
) is
begin
insert into DOMICILIO(
DIRECCION
,PRECIO
,TARJETA_CREDITO_NO_TARJ_CRED
,NOMBRE_PRODUCTO
,RESTAURANTE_ID_RESTAURANTE
,CELULAR
,ID_DOMICILO
,NOMBRECLIENTE
,CANTIDAD
) values (
p_DIRECCION
,p_PRECIO
,p_TARJETA_CREDITO_NO_TARJ_CRED
,p_NOMBRE_PRODUCTO
,p_RESTAURANTE_ID_RESTAURANTE
,p_CELULAR
,p_ID_DOMICILO
,p_NOMBRECLIENTE
,p_CANTIDAD
);end;
-- update
procedure upd (
p_DIRECCION in DOMICILIO.DIRECCION%type default null 
,p_PRECIO in DOMICILIO.PRECIO%type default null 
,p_TARJETA_CREDITO_NO_TARJ_CRED in DOMICILIO.TARJETA_CREDITO_NO_TARJ_CRED%type
,p_NOMBRE_PRODUCTO in DOMICILIO.NOMBRE_PRODUCTO%type default null 
,p_RESTAURANTE_ID_RESTAURANTE in DOMICILIO.RESTAURANTE_ID_RESTAURANTE%type
,p_CELULAR in DOMICILIO.CELULAR%type default null 
,p_ID_DOMICILO in DOMICILIO.ID_DOMICILO%type
,p_NOMBRECLIENTE in DOMICILIO.NOMBRECLIENTE%type default null 
,p_CANTIDAD in DOMICILIO.CANTIDAD%type default null 
) is
begin
update DOMICILIO set
DIRECCION = p_DIRECCION
,PRECIO = p_PRECIO
,TARJETA_CREDITO_NO_TARJ_CRED = p_TARJETA_CREDITO_NO_TARJ_CRED
,NOMBRE_PRODUCTO = p_NOMBRE_PRODUCTO
,RESTAURANTE_ID_RESTAURANTE = p_RESTAURANTE_ID_RESTAURANTE
,CELULAR = p_CELULAR
,NOMBRECLIENTE = p_NOMBRECLIENTE
,CANTIDAD = p_CANTIDAD
where ID_DOMICILO = p_ID_DOMICILO;
end;
-- del
procedure del (
p_ID_DOMICILO in DOMICILIO.ID_DOMICILO%type
) is
begin
delete from DOMICILIO
where ID_DOMICILO = p_ID_DOMICILO;
end;
end DOMICILIO_tapi;

/
--------------------------------------------------------
--  DDL for Package Body MESA_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "EDELBERTO2"."MESA_TAPI" 
is
-- insert
procedure ins (
p_DISPONIBILIDAD in MESA.DISPONIBILIDAD%type default null 
,p_NO_MESA in MESA.NO_MESA%type
) is
begin
insert into MESA(
DISPONIBILIDAD
,NO_MESA
) values (
p_DISPONIBILIDAD
,p_NO_MESA
);end;
-- update
procedure upd (
p_DISPONIBILIDAD in MESA.DISPONIBILIDAD%type default null 
,p_NO_MESA in MESA.NO_MESA%type
) is
begin
update MESA set
DISPONIBILIDAD = p_DISPONIBILIDAD
where NO_MESA = p_NO_MESA;
end;
-- del
procedure del (
p_NO_MESA in MESA.NO_MESA%type
) is
begin
delete from MESA
where NO_MESA = p_NO_MESA;
end;
end MESA_tapi;

/
--------------------------------------------------------
--  DDL for Package Body PRODUCTO_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "EDELBERTO2"."PRODUCTO_TAPI" 
is
-- insert
procedure ins (
p_NOMBRE_PRODUCTO in PRODUCTO.NOMBRE_PRODUCTO%type default null 
,p_COSTO in PRODUCTO.COSTO%type default null 
,p_ID_PRODUCTO in PRODUCTO.ID_PRODUCTO%type
,p_CANTIDAD in PRODUCTO.CANTIDAD%type default null 
) is
begin
insert into PRODUCTO(
NOMBRE_PRODUCTO
,COSTO
,ID_PRODUCTO
,CANTIDAD
) values (
p_NOMBRE_PRODUCTO
,p_COSTO
,p_ID_PRODUCTO
,p_CANTIDAD
);end;
-- update
procedure upd (
p_NOMBRE_PRODUCTO in PRODUCTO.NOMBRE_PRODUCTO%type default null 
,p_COSTO in PRODUCTO.COSTO%type default null 
,p_ID_PRODUCTO in PRODUCTO.ID_PRODUCTO%type
,p_CANTIDAD in PRODUCTO.CANTIDAD%type default null 
) is
begin
update PRODUCTO set
NOMBRE_PRODUCTO = p_NOMBRE_PRODUCTO
,COSTO = p_COSTO
,CANTIDAD = p_CANTIDAD
where ID_PRODUCTO = p_ID_PRODUCTO;
end;
-- del
procedure del (
p_ID_PRODUCTO in PRODUCTO.ID_PRODUCTO%type
) is
begin
delete from PRODUCTO
where ID_PRODUCTO = p_ID_PRODUCTO;
end;
end PRODUCTO_tapi;

/
--------------------------------------------------------
--  DDL for Package Body RESERVA_TAPI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "EDELBERTO2"."RESERVA_TAPI" 
is
-- insert
procedure ins (
p_TARJETA_CREDITO_NO_TARJ_CRED in RESERVA.TARJETA_CREDITO_NO_TARJ_CRED%type
,p_RESTAURANTE_ID_RESTAURANTE in RESERVA.RESTAURANTE_ID_RESTAURANTE%type
,p_FECHA in RESERVA.FECHA%type default null 
,p_ID_RESERVA in RESERVA.ID_RESERVA%type
,p_CANTIDAD_MESA in RESERVA.CANTIDAD_MESA%type default null 
,p_MESA_NO_MESA in RESERVA.MESA_NO_MESA%type
,p_NOMBRE in RESERVA.NOMBRE%type default null 
) is
begin
insert into RESERVA(
TARJETA_CREDITO_NO_TARJ_CRED
,RESTAURANTE_ID_RESTAURANTE
,FECHA
,ID_RESERVA
,CANTIDAD_MESA
,MESA_NO_MESA
,NOMBRE
) values (
p_TARJETA_CREDITO_NO_TARJ_CRED
,p_RESTAURANTE_ID_RESTAURANTE
,p_FECHA
,p_ID_RESERVA
,p_CANTIDAD_MESA
,p_MESA_NO_MESA
,p_NOMBRE
);end;
-- update
procedure upd (
p_TARJETA_CREDITO_NO_TARJ_CRED in RESERVA.TARJETA_CREDITO_NO_TARJ_CRED%type
,p_RESTAURANTE_ID_RESTAURANTE in RESERVA.RESTAURANTE_ID_RESTAURANTE%type
,p_FECHA in RESERVA.FECHA%type default null 
,p_ID_RESERVA in RESERVA.ID_RESERVA%type
,p_CANTIDAD_MESA in RESERVA.CANTIDAD_MESA%type default null 
,p_MESA_NO_MESA in RESERVA.MESA_NO_MESA%type
,p_NOMBRE in RESERVA.NOMBRE%type default null 
) is
begin
update RESERVA set
TARJETA_CREDITO_NO_TARJ_CRED = p_TARJETA_CREDITO_NO_TARJ_CRED
,RESTAURANTE_ID_RESTAURANTE = p_RESTAURANTE_ID_RESTAURANTE
,FECHA = p_FECHA
,CANTIDAD_MESA = p_CANTIDAD_MESA
,MESA_NO_MESA = p_MESA_NO_MESA
,NOMBRE = p_NOMBRE
where ID_RESERVA = p_ID_RESERVA;
end;
-- del
procedure del (
p_ID_RESERVA in RESERVA.ID_RESERVA%type
) is
begin
delete from RESERVA
where ID_RESERVA = p_ID_RESERVA;
end;
end RESERVA_tapi;

/
--------------------------------------------------------
--  Constraints for Table TARJETA_CREDITO
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."TARJETA_CREDITO" MODIFY ("NO_TARJ_CRED" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."TARJETA_CREDITO" ADD CONSTRAINT "TARJETA_CREDITO_PK" PRIMARY KEY ("NO_TARJ_CRED")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOMICILIO
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."DOMICILIO" MODIFY ("ID_DOMICILO" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."DOMICILIO" MODIFY ("RESTAURANTE_ID_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."DOMICILIO" MODIFY ("TARJETA_CREDITO_NO_TARJ_CRED" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."DOMICILIO" ADD CONSTRAINT "DOMICILIO_PK" PRIMARY KEY ("ID_DOMICILO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATOSTAREA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESTAURANTE
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."RESTAURANTE" MODIFY ("ID_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."RESTAURANTE" MODIFY ("ADMIN_ID_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."RESTAURANTE" ADD CONSTRAINT "RESTAURANTE_PK" PRIMARY KEY ("ID_RESTAURANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVA
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."RESERVA" MODIFY ("ID_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."RESERVA" MODIFY ("RESTAURANTE_ID_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."RESERVA" MODIFY ("TARJETA_CREDITO_NO_TARJ_CRED" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."RESERVA" MODIFY ("MESA_NO_MESA" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."RESERVA" ADD CONSTRAINT "RESERVA_PK" PRIMARY KEY ("ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MESA
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."MESA" MODIFY ("NO_MESA" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."MESA" ADD CONSTRAINT "MESA_PK" PRIMARY KEY ("NO_MESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_DOMICILIO
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."DETALLE_DOMICILIO" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."DETALLE_DOMICILIO" MODIFY ("DOMICILIO_ID_DOMICILO" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."DETALLE_DOMICILIO" MODIFY ("PRODUCTO_ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."DETALLE_DOMICILIO" ADD CONSTRAINT "DETALLE_DOMICILIO_PK" PRIMARY KEY ("ID_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATOSTAREA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."ADMIN" MODIFY ("ID_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "EDELBERTO2"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ID_ADMIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSTAREA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_DOMICILIO
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."DETALLE_DOMICILIO" ADD CONSTRAINT "DETALLE_DOMICILIO_DOMICILIO_FK" FOREIGN KEY ("DOMICILIO_ID_DOMICILO")
	  REFERENCES "EDELBERTO2"."DOMICILIO" ("ID_DOMICILO") ENABLE;
  ALTER TABLE "EDELBERTO2"."DETALLE_DOMICILIO" ADD CONSTRAINT "DETALLE_DOMICILIO_PRODUCTO_FK" FOREIGN KEY ("PRODUCTO_ID_PRODUCTO")
	  REFERENCES "EDELBERTO2"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOMICILIO
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."DOMICILIO" ADD CONSTRAINT "DOMICILIO_RESTAURANTE_FK" FOREIGN KEY ("RESTAURANTE_ID_RESTAURANTE")
	  REFERENCES "EDELBERTO2"."RESTAURANTE" ("ID_RESTAURANTE") ENABLE;
  ALTER TABLE "EDELBERTO2"."DOMICILIO" ADD CONSTRAINT "DOMICILIO_TARJETA_CREDITO_FK" FOREIGN KEY ("TARJETA_CREDITO_NO_TARJ_CRED")
	  REFERENCES "EDELBERTO2"."TARJETA_CREDITO" ("NO_TARJ_CRED") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVA
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."RESERVA" ADD CONSTRAINT "RESERVA_MESA_FK" FOREIGN KEY ("MESA_NO_MESA")
	  REFERENCES "EDELBERTO2"."MESA" ("NO_MESA") ENABLE;
  ALTER TABLE "EDELBERTO2"."RESERVA" ADD CONSTRAINT "RESERVA_RESTAURANTE_FK" FOREIGN KEY ("RESTAURANTE_ID_RESTAURANTE")
	  REFERENCES "EDELBERTO2"."RESTAURANTE" ("ID_RESTAURANTE") ENABLE;
  ALTER TABLE "EDELBERTO2"."RESERVA" ADD CONSTRAINT "RESERVA_TARJETA_CREDITO_FK" FOREIGN KEY ("TARJETA_CREDITO_NO_TARJ_CRED")
	  REFERENCES "EDELBERTO2"."TARJETA_CREDITO" ("NO_TARJ_CRED") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESTAURANTE
--------------------------------------------------------

  ALTER TABLE "EDELBERTO2"."RESTAURANTE" ADD CONSTRAINT "RESTAURANTE_ADMIN_FK" FOREIGN KEY ("ADMIN_ID_ADMIN")
	  REFERENCES "EDELBERTO2"."ADMIN" ("ID_ADMIN") ENABLE;
